### ISSUE TITLE
大哥，不行啊。报错

### ISSUE THREAD

**Issue by wahaobi** [maoxs2/open-grin-pool#1]
root@iZuf67dm90g2b0k3qix15mZ:~/epic# ./epic
badger 2019/09/10 01:59:45 INFO: All 0 tables opened in 0s
badger 2019/09/10 01:59:45 INFO: Replaying file id: 0 at offset: 0
badger 2019/09/10 01:59:45 INFO: Replay took: 2.917µs
badger 2019/09/10 01:59:45 DEBUG: Value log discard stats empty
2019/09/10 01:59:45 listen tcp: address 0.0.0.04654: missing port in address

**Comment by maoxs2** [comment]
bug fixed in following versions. I have pushed now. Thanks for reporting.

This open-sourcing version is not latest one which currently deployed on server.
