### ISSUE TITLE
revenue这个页面多久有显示

### ISSUE THREAD

**Issue by wahaobi** [maoxs2/open-grin-pool#11]
http://47.103.153.6:3333/revenue这个页面多久有显示

![image](https://user-images.githubusercontent.com/40647643/64916768-228a8080-d7b7-11e9-8664-d663d64a67f1.png)
![image](https://user-images.githubusercontent.com/40647643/64916769-3d5cf500-d7b7-11e9-9a44-60065c2f10d6.png)

**Comment by wahaobi** [comment]
![image](https://user-images.githubusercontent.com/40647643/64916884-b9a50780-d7ba-11e9-8cc5-76a5e78cf4be.png)
余额不显示

**Comment by maoxs2** [comment]
which commit?

**Comment by wahaobi** [comment]
![image](https://user-images.githubusercontent.com/40647643/64964097-fe20c800-d8cc-11e9-9e74-06d56799fa46.png)
调用不了矿工数据

**Comment by maoxs2** [comment]
missing `xhr.send(json);` after onload.

**Comment by maoxs2** [comment]
![image](https://user-images.githubusercontent.com/12538215/64966004-95d3e580-d8d0-11e9-92c0-65128e5f2eac.png)

**Comment by wahaobi** [comment]
![image](https://user-images.githubusercontent.com/40647643/64966125-c3b92a00-d8d0-11e9-9ad7-17ea723f251f.png)

**Comment by maoxs2** [comment]
`xhr.send();`, no `json`.

**Comment by maoxs2** [comment]
or using latest commit, I have fixed this

**Comment by wahaobi** [comment]
使用最新的提交，还是没有

**Comment by maoxs2** [comment]
I have saw your page. Please eift the `API` to your external ip and port

**Comment by wahaobi** [comment]
![image](https://user-images.githubusercontent.com/40647643/64967785-b3567e80-d8d3-11e9-9877-1bbd7e2309e5.png)

**Comment by maoxs2** [comment]
![image](https://user-images.githubusercontent.com/12538215/64968043-1516e880-d8d4-11e9-9539-57d8c6edcb0f.png)
besides, replace `"/miner"` with `"/miner/"

**Comment by wahaobi** [comment]
good
