### ISSUE TITLE
hashrate调用错误

### ISSUE THREAD

**Issue by wahaobi** [maoxs2/open-grin-pool#17]
![image](https://user-images.githubusercontent.com/40647643/64969838-41803400-d8d7-11e9-84cf-df2aa61c6126.png)
![image](https://user-images.githubusercontent.com/40647643/64969903-607ec600-d8d7-11e9-909a-a244bad4f28b.png)

**Comment by maoxs2** [comment]
take a try with latest master branch, thanks.

**Comment by wahaobi** [comment]
![image](https://user-images.githubusercontent.com/40647643/65012445-f18e8500-d949-11e9-9d09-eef9b9004976.png)

**Comment by maoxs2** [comment]
use 	`github.com/go-redis/redis v6.15.5+incompatible` please, dont using 7 or master
