### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by stepanovandrey89** [maoxs2/open-grin-pool#18]
pool@hostname:~$ cd pool && go build .
# _/home/pool/pool
./db.go:102:51: error: argument 2 has incompatible type
  _, err := db.client.ZAdd("tmp:"+login+":"+agent, z).Result()
                                                   ^
./db.go:262:46: error: argument 2 has incompatible type
   _, err := db.client.ZAdd("revenue:"+miner, z).Result()
                                              ^
go version go1.10.3 gccgo (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0 linux/amd64

**Comment by wahaobi** [comment]
INFO : 2019/09/18 00:18:24.686420 nodeStratumClient.go:48: Node returns a response: {"id":"0","jsonrpc":"2.0","method":"status","result":{"accepted":0,"difficulty":1,"height":23919,"id":"5412","rejected":0,"stale":0},"error":null}
ERROR: 2019/09/18 00:18:24.686716 db.go:175: redis: nil
panic: runtime error: integer divide by zero

goroutine 54 [running]:
main.(*database).setMinerAgentStatus(0xc420010030, 0xc42014e595, 0x5, 0xc42014e586, 0xa, 0xc3500, 0xc420170480)
	/root/epic/db.go:180 +0xaab
main.(*minerSession).handleMethod(0xc420060300, 0xc420138320, 0xc420010030)
	/root/epic/stratumServer.go:56 +0xcc
main.(*stratumServer).handleConn.func1(0xc4201e2000, 0x92, 0xa0)
	/root/epic/stratumServer.go:125 +0x1c6
created by main.(*nodeClient).registerHandler
	/root/epic/nodeStratumClient.go:50 +0x1ca
我能编成功，但是跑起来会出错。

**Comment by stepanovandrey89** [comment]
pool@hostname:~/pool$ sudo /usr/local/go/bin/go build .
go: finding github.com/gorilla/mux v1.7.3
go: finding github.com/go-redis/redis v6.15.5+incompatible
go: finding github.com/onsi/gomega v1.7.0
go: finding github.com/onsi/ginkgo v1.10.1
go: finding github.com/google/logger v1.0.1
go: finding golang.org/x/sys v0.0.0-20190904154756-749cb33beabd
go: finding golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: finding github.com/onsi/ginkgo v1.6.0
go: finding github.com/hpcloud/tail v1.0.0
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: finding github.com/golang/protobuf v1.2.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding gopkg.in/fsnotify.v1 v1.4.7
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/go-redis/redis v6.15.5+incompatible
go: downloading github.com/gorilla/mux v1.7.3
go: downloading github.com/google/logger v1.0.1
go: extracting github.com/google/logger v1.0.1
go: extracting github.com/gorilla/mux v1.7.3
go: extracting github.com/go-redis/redis v6.15.5+incompatible

**Comment by stepanovandrey89** [comment]
success

**Comment by wahaobi** [comment]
@stepanovandrey89 编成功了？编起来会出错吗。

**Comment by stepanovandrey89** [comment]
https://tecadmin.net/install-go-on-ubuntu/

**Comment by maoxs2** [comment]
@stepanovandrey89 update your golang to the later version of 1.11. Go intraduced the `go mod ` after 1.11 and that's what I'm using for package management.

**Comment by maoxs2** [comment]
I have add the deploy function from travis-ci, which means that you can get the latest binary from the release page without building by yourselves.
