### ISSUE TITLE
is this code tested?

### ISSUE THREAD

**Issue by yestop** [maoxs2/open-grin-pool#2]
how to edit the configure files? 
Is the pool works well?
thanks.

**Comment by maoxs2** [comment]
This bug have been fixed in the latest testing branch. Reason is that the miner sent status request before login, which leads to that the server closed the tcp conn with it.

**Comment by wahaobi** [comment]
> 此错误已在最新的测试分支中修复。原因是矿工在登录前发送了状态请求，这导致服务器用它关闭了tcp conn。

历害

**Comment by wahaobi** [comment]
> 此错误已在最新的测试分支中修复。原因是矿工在登录前发送了状态请求，这导致服务器用它关闭了tcp conn。

![image](https://user-images.githubusercontent.com/40647643/64855902-74b29100-d653-11e9-811f-72f265af4a88.png)
还是不行，你测试正常吗。我用20台挖了一天了，还是这样

**Comment by maoxs2** [comment]
Could you help me upload your `pool.log` here？ It would help me analysis the bug.

**Comment by wahaobi** [comment]
[epic-server.log](https://github.com/maoxs2/open-grin-pool/files/3609745/epic-server.log)

[epic.log](https://github.com/maoxs2/open-grin-pool/files/3609773/epic.log)

**Comment by maoxs2** [comment]
I notice there is no login request. So I think it's the problem on miner config. You can check the readme part in #4 .

**Comment by wahaobi** [comment]
晕，我刚发现，没开启，哈哈，感谢感谢
