### ISSUE TITLE
redis: can't parse reply="[\x00\x00\x00" reading string

### ISSUE THREAD

**Issue by M-Adeel-Danish** [maoxs2/open-grin-pool#32]
Hi @kevin070982 @maoxs2 @fossabot ,
Hope you guys are doing great,

I am not the best developer in the market, though I need this to work pretty badly. I am not familiar with in-depth go and Redis environments. Which means I will be here a lot. 

I have skimmed through the code and couldn't find DB migration. And Redis is apparently unable to communicate with DB. Because either no tables exist in DB or `dbname: 0` is causing some problem.
DB permission is anyuser@anyhost with password 

Function block with exception:
```
func initDB(config *config) *database {
	rdb := redis.NewClient(&redis.Options{
		Addr:     config.Storage.Address + ":" + strconv.Itoa(config.Storage.Port),
		Password: config.Storage.Password,
		DB:       config.Storage.Db,
	})

	_, err := rdb.Ping().Result()
	if err != nil {
		logger.Fatal(err)
	}
```
Exception;
`redis: can't parse reply="[\x00\x00\x00" reading string`

Here is storge section of `config.json`
```
  "storage": {
    "address": "127.0.0.1",
    "port": 3306,
    "db": 0,
    "password": "WtFt7PywcuxwGYEQ"
  },
```

Kindly guide me through my trial.
Sincerely,

**Comment by maoxs2** [comment]
You mean it throws a fatal on redis init?

I just have tried with config
```json
  "storage": {
    "address": "127.0.0.1",
    "port": 6379,
    "db": 0,
    "password": ""
  },
```
and no error throwed.

So I guess maybe you are treating the Redis database as MySQL database (port: 3306)? If so, I suggest you **google what redis is, reading [this](https://www.quora.com/Are-MySQL-and-Redis-the-same#) and then take a simple try on both**, then you will know the difference between them.

If you wanna do db migration between Redis and MySQL, it would be better to write another application to migrate the data, **pool is just a pool and not data server**. In my opinion, mysql is not light-weigh enough to assemble into this simple project. But if you need any help on pool or grin daemon, take an issue here and I'll be happy to help.

**Comment by M-Adeel-Danish** [comment]
The pool is Redis server dependent and I was using MySQL server. 😓
