### ISSUE TITLE
: xinbi has not logged in

### ISSUE THREAD

**Issue by wahaobi** [maoxs2/open-grin-pool#6]
WARN : 2019/09/13 20:52:33.253087 stratumServer.go:187: xinbi has not logged in
INFO : 2019/09/13 20:52:33.253897 stratumServer.go:145: 171.81.42.115:16879 sends a status request:{"id":"0","jsonrpc":"2.0","method":"status","params":null}
WARN : 2019/09/13 20:52:33.253931 stratumServer.go:187: xinbi has not logged in
INFO : 2019/09/13 20:52:33.253993 stratumServer.go:145: 171.81.42.115:42505 sends a status request:{"id":"0","jsonrpc":"2.0","method":"status","params":null}
WARN : 2019/09/13 20:52:33.254019 stratumServer.go:187: xinbi has not logged in
INFO : 2019/09/13 20:52:33.255494 stratumServer.go:145: 171.81.42.115:42517 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce":6287726918421042184,"pow":{"RandomX":[0,4,192,79,126,157,203,61,209,75,79,46,67,203,162,121,141,244,22,10,163,143,60,74,32,56,241,39,129,176,128,230]}}}
INFO : 2019/09/13 20:52:33.255569 stratumServer.go:145: 171.81.42.115:42517 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce":16548582905754212139,"pow":{"RandomX":[0,0,79,179,31,158,151,159,198,255,27,94,111,248,23,72,179,62,116,51,20,17,103,134,238,127,142,19,22,6,241,63]}}}
INFO : 2019/09/13 20:52:33.255624 stratumServer.go:145: 171.81.42.115:16888 sends a status request:{"id":"0","jsonrpc":"2.0","method":"status","params":null}
WARN : 2019/09/13 20:52:33.255648 stratumServer.go:187: xinbi has not logged in
INFO : 2019/09/13 20:52:33.259220 stratumServer.go:145: 171.81.42.115:16889 sends a status request:{"id":"0","jsonrpc":"2.0","method":"status","params":null}
WARN : 2019/09/13 20:52:33.259263 stratumServer.go:187: xinbi has not logged in
INFO : 2019/09/13 20:52:33.263575 stratumServer.go:145: 171.81.42.115:16880 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce":13702953554200028982,"pow":{"RandomX":[0,9,209,15,215,57,126,24,77,203,36,101,23,171,97,43,124,196,249,245,133,35,223,80,140,177,145,68,2,196,77,27]}}}
INFO : 2019/09/13 20:52:33.263664 stratumServer.go:145: 171.81.42.115:16887 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce":17788702597577268871,"pow":{"RandomX":[0,5,241,248,124,239,234,48,101,49,19,23,248,184,24,69,106,174,157,145,130,83,24,206,46,27,192,72,249,148,31,63]}}}
INFO : 2019/09/13 20:52:33.352183 stratumServer.go:145: 171.81.42.115:16748 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce":10896554535171352967,"pow":{"RandomX":[0,0,51,150,214,24,27,70,87,165,92,72,147,0,105,91,195,152,235,219,171,38,47,57,125,153,63,223,122,108,237,106]}}}
INFO : 2019/09/13 20:52:33.366062 stratumServer.go:145: 171.81.42.115:16884 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce":9379940626695891939,"pow":{"RandomX":[0,4,195,6,98,181,82,85,173,173,251,80,126,4,176,54,101,147,83,85,50,99,66,166,190,90,50,81,245,155,146,19]}}}
INFO : 2019/09/13 20:52:33.430148 stratumServer.go:145: 171.81.42.115:16879 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce":13012132950977089435,"pow":{"RandomX":[0,5,69,172,55,243,89,29,73,253,117,249,63,118,150,101,85,4,187,15,103,3,42,53,186,0,82,39,193,94,23,41]}}}
INFO : 2019/09/13 20:52:33.435500 stratumServer.go:145: 171.81.42.115:16882 sends a submit request:{"id":"0","jsonrpc":"2.0","method":"submit","params":{"height":17196,"job_id":1,"nonce"

我开启登陆了，还是不行

**Comment by maoxs2** [comment]
provide your log file plz

**Comment by wahaobi** [comment]
[epic.log](https://github.com/maoxs2/open-grin-pool/files/3610245/epic.log)

**Comment by maoxs2** [comment]
Check the commit c8e8268 , the exit after login problem had been solved then.

So update the pool will effect.
